# ----- DQ Token -----

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=["GC5EVQFVCNF5FPGMH33GBV7CXUXAIFOHECZSYZR3U5BETKBBIOEGGTUK"]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="DekCom Foundation"
ORG_DBA="DekCom Foundation"
ORG_URL="https://dq.dmg.st"
ORG_LOGO="https://dq.dmg.st/_uploads/dq.png"
ORG_DESCRIPTION="Since 1996 in Bangkok, Thailand"
ORG_PHYSICAL_ADDRESS="THAILAND"
ORG_PHONE_NUMBER="+6621073200"


[[PRINCIPALS]]
name="Damrongsak Sattabut"
email="me@dmg.st"
keybase="iLek2428"
twitter="iLek2428"
github="iLek2428"

# asset with meta info
[[CURRENCIES]]
code="DQ"
issuer="GBTTVI6GKDTO2BTWPMW74TYORUGBNAUVNGILEJ6FKJOZMWRXBGOJV4WN"
display_decimals=2
name="Digital Intelligence Quotient Token"
desc="1 DQ = 1 Intelligence"
conditions="Limited 10,000,000,000 DQ for everyone"
image="https://dq.dmg.st/_uploads/dq.png"
fixed_number=10000000000
