# ----- Untokens Project <untokens.github.io> -----

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=["GDBF76HEURTGVBN7HMGVY6XV34BBURP3J5XMHU5ZB4MDBQJMBAGD56AA", "GBL6DLARFDMYEHGUYRM6QDAF6ESSN54BHLR6PWLI34R4Z2A2JTPCWCAX", "GBRYAQL7IOOXVUPN43BC65ZDXQVPDBNHTPZN4CZSEB7YJGRARDPKRC2W"]

[DOCUMENTATION]
ORG_NAME="Untokens Project"
ORG_URL="untokens.github.io"
ORG_LOGO="https://untokens.github.io/uploads/noun_cryptocurrency_2123647.svg"
ORG_DESCRIPTION="Untokens Project is an issuer of 'unusual tokens' in the stellar network"

[[CURRENCIES]]
code="TIME"
issuer="GDBF76HEURTGVBN7HMGVY6XV34BBURP3J5XMHU5ZB4MDBQJMBAGD56AA"
display_decimals=2
name="Time"
desc="Planet earth is 454 billion years old, each one of them is represented by a time token. If time is money, now you can fill your wallet with it! Time tokens are freely traded on the stellar decentralized exchange."
image="https://untokens.github.io/uploads/noun_Planet_1377350.svg"
